---
output: html_document
editor_options: 
  chunk_output_type: console
---


This tests that the PacBio sequencer produces quality profiles similar
to inputs



```{r pacbio-setup, include=FALSE, cache = FALSE, eval = FALSE}
suppressPackageStartupMessages({
    library(jackalope)
    library(tidyverse)
})
knitr::opts_chunk$set(echo = FALSE, cache = FALSE, dev = 'quartz_pdf')
# knitr::opts_knit$set(root.dir = normalizePath(".."))
if (isTRUE(getOption('knitr.in.progress'))) knitr::knit_theme$set(knitr::knit_theme$get("acid"))
if (!isTRUE(getOption('knitr.in.progress'))) {
    options("device" = "quartz")
    grDevices::graphics.off()
}
theme_set(theme_classic() + 
              theme(legend.background = element_blank(),
                    strip.background = element_blank(),
                    plot.margin = margin(0.5, 0.5, 0.5, 0.5)))

# Saves our temporary directory to store some files:
dir <- paste0(tempdir(check = TRUE), "/")

```




## Read lengths - default parameter values

For this section, I simulated 100,000 PacBio reads under default parameters.
I then compared the read lengths to the expected read-length distribution:

$$
\log(L - \delta) \sim \text{N}(\mu, \sigma)
$$



```{r pacbio-read-lengths_cap}
rl_cap <- paste("Read length distribution observed from 100,000 generated reads",
                "(histogram; left y-axis), alongside the frequency distribution",
                "as predicted for default parameters (dashed line; right y-axis).")
```


```{r pacbio-read-lengths, fig.height=3, fig.width=5, fig.cap=rl_cap}
# 4 sequences of length 100e3
seq <- sapply(c("T", "C", "A", "G"), function(nt) paste(rep(nt, 100e3), collapse = ""))

# Make ref_genome object from a pointer to a RefGenome object based on `seqs`
rg <- ref_genome$new(jackalope:::make_ref_genome(seq))

pacbio(rg, out_prefix = paste0(dir, "test_pb"), n_reads = 10e3)

fq <- readLines(paste0(dir, "test_pb_R1.fq"))
read_lens <- nchar(fq[seq(2, length(fq), 4)])


# Looking at default read length distribution:

# Defaults from SimLoRD:
test_lens <- function(obs, mult = 1) {
  pars <- list(sigma = 0.200110276521, loc = -10075.4363813, scale = 17922.611306,
               min_len = 50)
  .x <- seq(pars$min_len, max(obs), length.out = length(obs))
  .z <- mult * dlnorm(.x - pars$loc, log(pars$scale), pars$sigma)
  return(.z)
}


tibble(obs = nchar(fq[seq(2, length(fq), 4)])) %>%
    ggplot(aes(obs)) +
    # geom_freqpoly(bins = 50, size = 1, color = "dodgerblue") +
    geom_histogram(bins = 50, fill = "dodgerblue", color = "gray70", size = 0.1) +
    stat_function(fun = test_lens, args = list(mult = 6e6), color = "black",
                  linetype = 2, size = 1) +
    theme_classic() +
    theme(legend.position = c(0.75, 0.75),
          legend.text = element_text(size = 11)) +
    scale_color_brewer(NULL, palette = "Dark2") +
    # ggtitle("Read length distributions") +
    scale_y_continuous("Count",
                       sec.axis = sec_axis(~./6e6, name = "Density")) +
    scale_x_continuous("Read length (kb)",
                       breaks = seq(0, 30e3, 10e3), labels = seq(0, 30, 10))
```


## Read lengths - non-default parameters

```{r pacbio-read-lengths-non-defaults}

# Looking at non-default read length distribution

rl_mat <- cbind(seq(100, 1e4, 100), runif(100))
rl_mat[,2] <- rl_mat[,2] / sum(rl_mat[,2])
pacbio(rg, out_prefix = paste0(dir, "test_pb_nd"), n_reads = 10e3,
       custom_read_lengths = rl_mat)

fq_nd <- readLines(paste0(dir, "test_pb_nd_R1.fq"))
read_lens <- nchar(fq_nd[seq(2, length(fq_nd), 4)])


# Plotting observed vs predicted:

ndrl_df <- tibble(obs = as.integer(table(read_lens)),
                  pred = length(read_lens) * rl_mat[,2])

lims <- range(c(ndrl_df$obs, ndrl_df$pred))

ndrl_df %>%
    ggplot(aes((pred), (obs))) +
    geom_point() +
    geom_abline(slope = 1, intercept = 0, linetype = 2, color = "firebrick2") +
    scale_x_continuous("Predicted read length count",
                       limits = lims) +
    scale_y_continuous("Observed read length count",
                       limits = lims) +
    theme_classic() +
    coord_equal()

```





## Read qualities

```{r pacbio-quals}
Rcpp::sourceCpp("supp/diagnostics-pacbio.cpp")

fq <- readLines(paste0(dir, "test_pb_R1.fq"))
read_lens <- nchar(fq[seq(2, length(fq), 4)])

quals <- fq[seq(4, length(fq), 4)]
# Mean quality by read:
m_quals <- mean_quals(quals)

# This looks approximately like the SimLoRD panel in Fig. 1 in the paper,
# so I'm pretty satisfied.
# The extra reads of short length here are likely a result of either the way they plotted
# things in the original paper or that they used the genome of *Neurospora crassa*
# rather than simulated reads.


tibble(qual = m_quals, len = read_lens) %>%
    ggplot(aes(len, qual)) +
    geom_hex(bins = 50) +
    xlab("Read length") +
    ylab("Read quality\n(average base quality)") +
    theme_classic() +
    theme(legend.position = c(0.75, 0.5))

```